-- Global Foods
INSERT INTO global_foods (food_key, data)
VALUES
('puttu', '{"name":"Puttu","cals":330,"p":4,"c":68,"f":3,"unit":"item","category":"breakfast","emoji":"🥖"}'::jsonb),
('appam', '{"name":"Appam","cals":120,"p":2,"c":25,"f":1,"unit":"item","category":"breakfast","emoji":"🥞"}'::jsonb),
('dosa', '{"name":"Dosa","cals":168,"p":4,"c":29,"f":4,"unit":"item","category":"breakfast","emoji":"🥞"}'::jsonb),
('masala_dosa', '{"name":"Masala Dosa","cals":415,"p":8,"c":54,"f":18,"unit":"item","category":"breakfast","emoji":"🥞"}'::jsonb),
('rava_dosa', '{"name":"Rava Dosa","cals":200,"p":5,"c":32,"f":5,"unit":"item","category":"breakfast","emoji":"🥞"}'::jsonb),
('idli', '{"name":"Idli","cals":58,"p":2,"c":12,"f":0,"unit":"item","category":"breakfast","emoji":"🥟"}'::jsonb),
('idiyappam', '{"name":"Idiyappam","cals":110,"p":2,"c":24,"f":0,"unit":"item","category":"breakfast","emoji":"🍝"}'::jsonb),
('upma', '{"name":"Upma","cals":190,"p":4,"c":28,"f":6,"unit":"bowl","category":"breakfast","emoji":"🥣"}'::jsonb),
('poha', '{"name":"Poha","cals":250,"p":5,"c":45,"f":5,"unit":"bowl","category":"breakfast","emoji":"🍛"}'::jsonb),
('vada', '{"name":"Vada","cals":140,"p":4,"c":15,"f":7,"unit":"item","category":"breakfast","emoji":"🍩"}'::jsonb),
('uttapam', '{"name":"Uttapam","cals":200,"p":5,"c":35,"f":4,"unit":"item","category":"breakfast","emoji":"🥞"}'::jsonb),
('pesarattu', '{"name":"Pesarattu","cals":170,"p":7,"c":25,"f":4,"unit":"item","category":"breakfast","emoji":"🥞"}'::jsonb),
('pongal', '{"name":"Ven Pongal","cals":300,"p":7,"c":45,"f":10,"unit":"bowl","category":"breakfast","emoji":"🍛"}'::jsonb),
('aval_nanachathu', '{"name":"Aval Nanachathu","cals":150,"p":2,"c":30,"f":2,"unit":"bowl","category":"breakfast","emoji":"🥣"}'::jsonb),
('bread_toast', '{"name":"Bread Toast","cals":75,"p":3,"c":13,"f":1,"unit":"slice","category":"breakfast","emoji":"🍞"}'::jsonb),
('cornflakes', '{"name":"Cornflakes (with milk)","cals":200,"p":6,"c":35,"f":3,"unit":"bowl","category":"breakfast","emoji":"🥣"}'::jsonb),
('oats_porridge', '{"name":"Oats Porridge","cals":150,"p":5,"c":27,"f":3,"unit":"bowl","category":"breakfast","emoji":"🥣"}'::jsonb),
('egg_omelette', '{"name":"Egg Omelette (2 eggs)","cals":180,"p":12,"c":1,"f":14,"unit":"item","category":"breakfast","emoji":"🍳"}'::jsonb),
('paratha_plain', '{"name":"Plain Paratha","cals":260,"p":5,"c":35,"f":10,"unit":"item","category":"breakfast","emoji":"🫓"}'::jsonb),
('aloo_paratha', '{"name":"Aloo Paratha","cals":300,"p":6,"c":45,"f":10,"unit":"item","category":"breakfast","emoji":"🫓"}'::jsonb),
('paneer_paratha', '{"name":"Paneer Paratha","cals":320,"p":12,"c":35,"f":14,"unit":"item","category":"breakfast","emoji":"🫓"}'::jsonb),
('french_toast', '{"name":"French Toast","cals":220,"p":8,"c":25,"f":10,"unit":"item","category":"breakfast","emoji":"🥪"}'::jsonb),
('sandwich_basic', '{"name":"Basic Veg Sandwich","cals":250,"p":6,"c":40,"f":8,"unit":"item","category":"breakfast","emoji":"🥪"}'::jsonb),
('white_rice', '{"name":"White Rice (Cooked)","cals":130,"p":2,"c":28,"f":0,"unit":"g","category":"rice","emoji":"🍚"}'::jsonb),
('brown_rice', '{"name":"Brown Rice (Cooked)","cals":111,"p":2,"c":23,"f":0,"unit":"g","category":"rice","emoji":"🍚"}'::jsonb),
('chicken_biriyani', '{"name":"Chicken Biriyani","cals":350,"p":15,"c":40,"f":14,"unit":"g","category":"rice","emoji":"🥘"}'::jsonb),
('mutton_biriyani', '{"name":"Mutton Biriyani","cals":400,"p":18,"c":38,"f":18,"unit":"g","category":"rice","emoji":"🥘"}'::jsonb),
('veg_biriyani', '{"name":"Veg Biriyani","cals":250,"p":5,"c":40,"f":8,"unit":"g","category":"rice","emoji":"🥘"}'::jsonb),
('egg_fried_rice', '{"name":"Egg Fried Rice","cals":280,"p":8,"c":35,"f":10,"unit":"g","category":"rice","emoji":"🍚"}'::jsonb),
('chicken_fried_rice', '{"name":"Chicken Fried Rice","cals":320,"p":12,"c":35,"f":12,"unit":"g","category":"rice","emoji":"🍚"}'::jsonb),
('veg_pulao', '{"name":"Veg Pulao","cals":220,"p":5,"c":38,"f":6,"unit":"g","category":"rice","emoji":"🍚"}'::jsonb),
('khichdi', '{"name":"Khichdi","cals":180,"p":6,"c":30,"f":4,"unit":"g","category":"rice","emoji":"🍛"}'::jsonb),
('lemon_rice', '{"name":"Lemon Rice","cals":210,"p":4,"c":35,"f":6,"unit":"g","category":"rice","emoji":"🍚"}'::jsonb),
('curd_rice', '{"name":"Curd Rice","cals":160,"p":4,"c":25,"f":4,"unit":"g","category":"rice","emoji":"🍚"}'::jsonb),
('tamarind_rice', '{"name":"Tamarind Rice","cals":220,"p":4,"c":35,"f":7,"unit":"g","category":"rice","emoji":"🍚"}'::jsonb),
('jeera_rice', '{"name":"Jeera Rice","cals":200,"p":4,"c":35,"f":5,"unit":"g","category":"rice","emoji":"🍚"}'::jsonb),
('bisibelebath', '{"name":"Bisi Bele Bath","cals":250,"p":7,"c":40,"f":6,"unit":"g","category":"rice","emoji":"🍛"}'::jsonb),
('pongal_rice', '{"name":"Pongal (Sweet)","cals":320,"p":4,"c":55,"f":10,"unit":"g","category":"rice","emoji":"🍚"}'::jsonb),
('chapati', '{"name":"Chapati","cals":104,"p":3,"c":22,"f":0,"unit":"item","category":"breads","emoji":"🫓"}'::jsonb),
('kerala_parotta', '{"name":"Kerala Parotta","cals":340,"p":5,"c":40,"f":15,"unit":"item","category":"breads","emoji":"🫓"}'::jsonb),
('malabar_parotta', '{"name":"Malabar Parotta","cals":340,"p":5,"c":40,"f":15,"unit":"item","category":"breads","emoji":"🫓"}'::jsonb),
('naan', '{"name":"Naan","cals":260,"p":8,"c":42,"f":5,"unit":"item","category":"breads","emoji":"🫓"}'::jsonb),
('garlic_naan', '{"name":"Garlic Naan","cals":300,"p":8,"c":42,"f":10,"unit":"item","category":"breads","emoji":"🫓"}'::jsonb),
('puri', '{"name":"Puri","cals":140,"p":2,"c":15,"f":8,"unit":"item","category":"breads","emoji":"🫓"}'::jsonb),
('phulka', '{"name":"Phulka","cals":80,"p":3,"c":15,"f":0,"unit":"item","category":"breads","emoji":"🫓"}'::jsonb),
('roti', '{"name":"Roti (Tandoori)","cals":120,"p":4,"c":24,"f":1,"unit":"item","category":"breads","emoji":"🫓"}'::jsonb),
('kulcha', '{"name":"Kulcha","cals":220,"p":6,"c":38,"f":4,"unit":"item","category":"breads","emoji":"🫓"}'::jsonb),
('rumali_roti', '{"name":"Rumali Roti","cals":180,"p":5,"c":32,"f":3,"unit":"item","category":"breads","emoji":"🫓"}'::jsonb),
('bread_slice', '{"name":"White Bread","cals":75,"p":2,"c":14,"f":1,"unit":"slice","category":"breads","emoji":"🍞"}'::jsonb),
('bun', '{"name":"Bun","cals":150,"p":4,"c":28,"f":2,"unit":"item","category":"breads","emoji":"🥖"}'::jsonb),
('tortilla_wrap', '{"name":"Tortilla Wrap","cals":170,"p":4,"c":28,"f":4,"unit":"item","category":"breads","emoji":"🌯"}'::jsonb),
('sambar', '{"name":"Sambar","cals":80,"p":4,"c":12,"f":2,"unit":"bowl","category":"curries","emoji":"🍲"}'::jsonb),
('rasam', '{"name":"Rasam","cals":40,"p":1,"c":8,"f":1,"unit":"bowl","category":"curries","emoji":"🍲"}'::jsonb),
('kadala_curry', '{"name":"Kadala Curry","cals":220,"p":8,"c":28,"f":8,"unit":"bowl","category":"curries","emoji":"🥘"}'::jsonb),
('chicken_curry', '{"name":"Chicken Curry","cals":240,"p":15,"c":8,"f":16,"unit":"bowl","category":"curries","emoji":"🥘"}'::jsonb),
('mutton_curry', '{"name":"Mutton Curry","cals":300,"p":18,"c":8,"f":22,"unit":"bowl","category":"curries","emoji":"🥘"}'::jsonb),
('fish_curry', '{"name":"Fish Curry","cals":180,"p":14,"c":6,"f":10,"unit":"bowl","category":"curries","emoji":"🥘"}'::jsonb),
('egg_curry', '{"name":"Egg Curry (2 eggs)","cals":220,"p":14,"c":10,"f":14,"unit":"bowl","category":"curries","emoji":"🥘"}'::jsonb),
('prawn_curry', '{"name":"Prawn Curry","cals":200,"p":16,"c":8,"f":10,"unit":"bowl","category":"curries","emoji":"🥘"}'::jsonb),
('paneer_butter_masala', '{"name":"Paneer Butter Masala","cals":350,"p":12,"c":15,"f":28,"unit":"bowl","category":"curries","emoji":"🥘"}'::jsonb),
('dal_tadka', '{"name":"Dal Tadka","cals":180,"p":8,"c":22,"f":6,"unit":"bowl","category":"curries","emoji":"🍲"}'::jsonb),
('dal_makhani', '{"name":"Dal Makhani","cals":280,"p":10,"c":25,"f":16,"unit":"bowl","category":"curries","emoji":"🍲"}'::jsonb),
('rajma', '{"name":"Rajma Masala","cals":220,"p":10,"c":30,"f":6,"unit":"bowl","category":"curries","emoji":"🥘"}'::jsonb),
('chana_masala', '{"name":"Chana Masala","cals":240,"p":10,"c":35,"f":8,"unit":"bowl","category":"curries","emoji":"🥘"}'::jsonb),
('aloo_gobi', '{"name":"Aloo Gobi","cals":150,"p":4,"c":20,"f":6,"unit":"bowl","category":"curries","emoji":"🥘"}'::jsonb),
('palak_paneer', '{"name":"Palak Paneer","cals":280,"p":14,"c":10,"f":22,"unit":"bowl","category":"curries","emoji":"🥘"}'::jsonb),
('malai_kofta', '{"name":"Malai Kofta","cals":400,"p":10,"c":30,"f":28,"unit":"bowl","category":"curries","emoji":"🥘"}'::jsonb),
('avial', '{"name":"Avial","cals":180,"p":4,"c":15,"f":12,"unit":"bowl","category":"curries","emoji":"🍲"}'::jsonb),
('thoran', '{"name":"Cabbage/Beans Thoran","cals":120,"p":2,"c":10,"f":8,"unit":"bowl","category":"curries","emoji":"🥗"}'::jsonb),
('kootu_curry', '{"name":"Kootu Curry","cals":200,"p":6,"c":25,"f":8,"unit":"bowl","category":"curries","emoji":"🍲"}'::jsonb),
('beef_curry', '{"name":"Beef Curry","cals":280,"p":20,"c":8,"f":18,"unit":"bowl","category":"curries","emoji":"🥘"}'::jsonb),
('butter_chicken', '{"name":"Butter Chicken","cals":400,"p":18,"c":15,"f":30,"unit":"bowl","category":"curries","emoji":"🥘"}'::jsonb),
('chettinad_chicken', '{"name":"Chettinad Chicken","cals":280,"p":18,"c":12,"f":16,"unit":"bowl","category":"curries","emoji":"🥘"}'::jsonb),
('egg_roast', '{"name":"Egg Roast (2 eggs)","cals":240,"p":14,"c":12,"f":15,"unit":"bowl","category":"curries","emoji":"🥘"}'::jsonb),
('stew_veg', '{"name":"Veg Stew","cals":180,"p":3,"c":15,"f":12,"unit":"bowl","category":"curries","emoji":"🍲"}'::jsonb),
('stew_chicken', '{"name":"Chicken Stew","cals":280,"p":16,"c":12,"f":18,"unit":"bowl","category":"curries","emoji":"🥘"}'::jsonb),
('chicken_breast', '{"name":"Chicken Breast (Raw)","cals":165,"p":31,"c":0,"f":3,"unit":"g","category":"protein","emoji":"🍗"}'::jsonb),
('whole_egg', '{"name":"Whole Egg","cals":72,"p":6,"c":0,"f":5,"unit":"item","category":"protein","emoji":"🥚"}'::jsonb),
('egg_white', '{"name":"Egg White","cals":17,"p":4,"c":0,"f":0,"unit":"item","category":"protein","emoji":"🥚"}'::jsonb),
('paneer', '{"name":"Paneer (Raw)","cals":296,"p":14,"c":3,"f":25,"unit":"g","category":"protein","emoji":"🧀"}'::jsonb),
('tofu', '{"name":"Tofu (Firm)","cals":144,"p":15,"c":3,"f":8,"unit":"g","category":"protein","emoji":"🧊"}'::jsonb),
('fish_fillet', '{"name":"White Fish Fillet","cals":105,"p":20,"c":0,"f":2,"unit":"g","category":"protein","emoji":"🐟"}'::jsonb),
('prawns_grilled', '{"name":"Prawns (Grilled)","cals":120,"p":24,"c":0,"f":2,"unit":"g","category":"protein","emoji":"🦐"}'::jsonb),
('mutton', '{"name":"Mutton (Lean)","cals":143,"p":21,"c":0,"f":6,"unit":"g","category":"protein","emoji":"🥩"}'::jsonb),
('beef', '{"name":"Beef (Lean)","cals":250,"p":26,"c":0,"f":15,"unit":"g","category":"protein","emoji":"🥩"}'::jsonb),
('soya_chunks', '{"name":"Soya Chunks (Raw)","cals":345,"p":52,"c":33,"f":0,"unit":"g","category":"protein","emoji":"🥜"}'::jsonb),
('curd_plain', '{"name":"Curd (Plain, Cow)","cals":60,"p":3,"c":4,"f":3,"unit":"g","category":"protein","emoji":"🥣"}'::jsonb),
('greek_yogurt', '{"name":"Greek Yogurt (Plain)","cals":95,"p":10,"c":4,"f":4,"unit":"g","category":"protein","emoji":"🥣"}'::jsonb),
('cottage_cheese', '{"name":"Cottage Cheese","cals":98,"p":11,"c":3,"f":4,"unit":"g","category":"protein","emoji":"🧀"}'::jsonb),
('lentils_cooked', '{"name":"Lentils (Cooked)","cals":116,"p":9,"c":20,"f":0,"unit":"g","category":"protein","emoji":"🍲"}'::jsonb),
('chickpeas_cooked', '{"name":"Chickpeas (Cooked)","cals":164,"p":8,"c":27,"f":2,"unit":"g","category":"protein","emoji":"🧆"}'::jsonb),
('kidney_beans', '{"name":"Kidney Beans (Cooked)","cals":127,"p":8,"c":22,"f":0,"unit":"g","category":"protein","emoji":"🫘"}'::jsonb),
('tuna_canned', '{"name":"Tuna (Canned in water)","cals":116,"p":25,"c":0,"f":0,"unit":"g","category":"protein","emoji":"🐟"}'::jsonb),
('salmon', '{"name":"Salmon (Raw)","cals":208,"p":20,"c":0,"f":13,"unit":"g","category":"protein","emoji":"🍣"}'::jsonb),
('turkey_breast', '{"name":"Turkey Breast","cals":135,"p":30,"c":0,"f":1,"unit":"g","category":"protein","emoji":"🦃"}'::jsonb),
('chicken_thigh', '{"name":"Chicken Thigh","cals":209,"p":24,"c":0,"f":12,"unit":"g","category":"protein","emoji":"🍗"}'::jsonb),
('pork_chop', '{"name":"Pork Chop","cals":231,"p":24,"c":0,"f":14,"unit":"g","category":"protein","emoji":"🥩"}'::jsonb),
('mixed_salad', '{"name":"Mixed Salad","cals":20,"p":1,"c":4,"f":0,"unit":"bowl","category":"vegetables","emoji":"🥗"}'::jsonb),
('cucumber', '{"name":"Cucumber","cals":15,"p":0,"c":3,"f":0,"unit":"g","category":"vegetables","emoji":"🥒"}'::jsonb),
('cabbage_thoran', '{"name":"Cabbage Thoran","cals":100,"p":2,"c":8,"f":7,"unit":"bowl","category":"vegetables","emoji":"🥗"}'::jsonb),
('beans_stir_fry', '{"name":"Green Beans Stir Fry","cals":90,"p":2,"c":7,"f":6,"unit":"bowl","category":"vegetables","emoji":"🥗"}'::jsonb),
('carrot_raw', '{"name":"Carrot (Raw)","cals":41,"p":0,"c":9,"f":0,"unit":"g","category":"vegetables","emoji":"🥕"}'::jsonb),
('broccoli', '{"name":"Broccoli","cals":34,"p":2,"c":6,"f":0,"unit":"g","category":"vegetables","emoji":"🥦"}'::jsonb),
('spinach_cooked', '{"name":"Spinach (Cooked)","cals":23,"p":3,"c":3,"f":0,"unit":"g","category":"vegetables","emoji":"🥬"}'::jsonb),
('mixed_vegetables', '{"name":"Mixed Vegetables","cals":65,"p":2,"c":14,"f":0,"unit":"g","category":"vegetables","emoji":"🥗"}'::jsonb),
('bean_sprouts', '{"name":"Bean Sprouts","cals":30,"p":3,"c":6,"f":0,"unit":"g","category":"vegetables","emoji":"🌱"}'::jsonb),
('capsicum', '{"name":"Capsicum / Bell Pepper","cals":20,"p":0,"c":4,"f":0,"unit":"g","category":"vegetables","emoji":"🫑"}'::jsonb),
('mushroom', '{"name":"Mushroom (Raw)","cals":22,"p":3,"c":3,"f":0,"unit":"g","category":"vegetables","emoji":"🍄"}'::jsonb),
('corn_boiled', '{"name":"Sweet Corn (Boiled)","cals":96,"p":3,"c":21,"f":1,"unit":"g","category":"vegetables","emoji":"🌽"}'::jsonb),
('beetroot', '{"name":"Beetroot","cals":43,"p":1,"c":9,"f":0,"unit":"g","category":"vegetables","emoji":"🍠"}'::jsonb),
('sweet_potato', '{"name":"Sweet Potato","cals":86,"p":1,"c":20,"f":0,"unit":"g","category":"vegetables","emoji":"🍠"}'::jsonb),
('potato_boiled', '{"name":"Potato (Boiled)","cals":87,"p":1,"c":20,"f":0,"unit":"g","category":"vegetables","emoji":"🥔"}'::jsonb),
('chicken_burger', '{"name":"Chicken Burger","cals":450,"p":20,"c":45,"f":20,"unit":"item","category":"fastfood","emoji":"🍔"}'::jsonb),
('veg_burger', '{"name":"Veg Burger","cals":350,"p":8,"c":45,"f":15,"unit":"item","category":"fastfood","emoji":"🍔"}'::jsonb),
('pizza_slice', '{"name":"Pizza (1 Slice)","cals":280,"p":12,"c":30,"f":12,"unit":"slice","category":"fastfood","emoji":"🍕"}'::jsonb),
('french_fries', '{"name":"French Fries (Med)","cals":380,"p":4,"c":48,"f":18,"unit":"item","category":"fastfood","emoji":"🍟"}'::jsonb),
('samosa', '{"name":"Samosa","cals":250,"p":4,"c":25,"f":15,"unit":"item","category":"fastfood","emoji":"🥟"}'::jsonb),
('vada_pav', '{"name":"Vada Pav","cals":300,"p":6,"c":40,"f":12,"unit":"item","category":"fastfood","emoji":"🍔"}'::jsonb),
('pav_bhaji', '{"name":"Pav Bhaji","cals":400,"p":8,"c":50,"f":18,"unit":"plate","category":"fastfood","emoji":"🥘"}'::jsonb),
('chole_bhature', '{"name":"Chole Bhature","cals":600,"p":12,"c":65,"f":30,"unit":"plate","category":"fastfood","emoji":"🫓"}'::jsonb),
('chicken_roll', '{"name":"Chicken Roll","cals":450,"p":20,"c":45,"f":20,"unit":"item","category":"fastfood","emoji":"🌯"}'::jsonb),
('shawarma', '{"name":"Chicken Shawarma","cals":500,"p":25,"c":45,"f":22,"unit":"item","category":"fastfood","emoji":"🥙"}'::jsonb),
('momos_chicken', '{"name":"Chicken Momos (6)","cals":250,"p":15,"c":30,"f":8,"unit":"plate","category":"fastfood","emoji":"🥟"}'::jsonb),
('momos_veg', '{"name":"Veg Momos (6)","cals":200,"p":5,"c":35,"f":4,"unit":"plate","category":"fastfood","emoji":"🥟"}'::jsonb),
('spring_roll', '{"name":"Spring Roll","cals":150,"p":3,"c":15,"f":8,"unit":"item","category":"fastfood","emoji":"🌯"}'::jsonb),
('maggi_noodles', '{"name":"Maggi Noodles (1 Pack)","cals":350,"p":8,"c":50,"f":14,"unit":"bowl","category":"fastfood","emoji":"🍜"}'::jsonb),
('hot_dog', '{"name":"Hot Dog","cals":300,"p":10,"c":25,"f":18,"unit":"item","category":"fastfood","emoji":"🌭"}'::jsonb),
('chicken_nuggets', '{"name":"Chicken Nuggets (6)","cals":280,"p":14,"c":16,"f":18,"unit":"item","category":"fastfood","emoji":"🍗"}'::jsonb),
('onion_rings', '{"name":"Onion Rings","cals":400,"p":4,"c":45,"f":22,"unit":"plate","category":"fastfood","emoji":"🧅"}'::jsonb),
('doner_kebab', '{"name":"Doner Kebab Wrap","cals":550,"p":28,"c":50,"f":25,"unit":"item","category":"fastfood","emoji":"🥙"}'::jsonb),
('falafel_wrap', '{"name":"Falafel Wrap","cals":450,"p":12,"c":55,"f":20,"unit":"item","category":"fastfood","emoji":"🌯"}'::jsonb),
('grilled_sandwich', '{"name":"Grilled Veg Sandwich","cals":350,"p":8,"c":45,"f":15,"unit":"item","category":"fastfood","emoji":"🥪"}'::jsonb),
('chai_milk', '{"name":"Tea (with milk/sugar)","cals":80,"p":2,"c":12,"f":2,"unit":"cup","category":"beverages","emoji":"☕"}'::jsonb),
('black_coffee', '{"name":"Black Coffee","cals":5,"p":0,"c":1,"f":0,"unit":"cup","category":"beverages","emoji":"☕"}'::jsonb),
('filter_coffee', '{"name":"Filter Coffee","cals":90,"p":3,"c":12,"f":3,"unit":"cup","category":"beverages","emoji":"☕"}'::jsonb),
('green_tea', '{"name":"Green Tea","cals":2,"p":0,"c":0,"f":0,"unit":"cup","category":"beverages","emoji":"🍵"}'::jsonb),
('orange_juice', '{"name":"Orange Juice (Fresh)","cals":110,"p":1,"c":26,"f":0,"unit":"cup","category":"beverages","emoji":"🧃"}'::jsonb),
('mango_lassi', '{"name":"Mango Lassi","cals":250,"p":5,"c":45,"f":6,"unit":"cup","category":"beverages","emoji":"🥭"}'::jsonb),
('buttermilk', '{"name":"Buttermilk / Chaas","cals":40,"p":2,"c":5,"f":1,"unit":"cup","category":"beverages","emoji":"🥛"}'::jsonb),
('coconut_water', '{"name":"Coconut Water","cals":45,"p":0,"c":10,"f":0,"unit":"cup","category":"beverages","emoji":"🥥"}'::jsonb),
('protein_shake', '{"name":"Whey Protein (Water)","cals":120,"p":24,"c":3,"f":1,"unit":"scoop","category":"beverages","emoji":"🥤"}'::jsonb),
('whole_milk', '{"name":"Whole Milk","cals":150,"p":8,"c":12,"f":8,"unit":"cup","category":"beverages","emoji":"🥛"}'::jsonb),
('skim_milk', '{"name":"Skim Milk","cals":80,"p":8,"c":12,"f":0,"unit":"cup","category":"beverages","emoji":"🥛"}'::jsonb),
('cola_soda', '{"name":"Cola (Regular)","cals":140,"p":0,"c":39,"f":0,"unit":"cup","category":"beverages","emoji":"🥤"}'::jsonb),
('beer', '{"name":"Beer (Pint)","cals":150,"p":1,"c":13,"f":0,"unit":"cup","category":"beverages","emoji":"🍺"}'::jsonb),
('lime_soda', '{"name":"Fresh Lime Soda (Sweet)","cals":120,"p":0,"c":30,"f":0,"unit":"cup","category":"beverages","emoji":"🥤"}'::jsonb),
('smoothie_banana', '{"name":"Banana Smoothie","cals":250,"p":6,"c":45,"f":5,"unit":"cup","category":"beverages","emoji":"🍌"}'::jsonb),
('payasam', '{"name":"Payasam / Kheer","cals":280,"p":5,"c":45,"f":8,"unit":"bowl","category":"sweets","emoji":"🥣"}'::jsonb),
('halwa_carrot', '{"name":"Gajar Halwa","cals":320,"p":4,"c":45,"f":14,"unit":"bowl","category":"sweets","emoji":"🥧"}'::jsonb),
('ladoo_besan', '{"name":"Besan Ladoo","cals":180,"p":3,"c":22,"f":9,"unit":"item","category":"sweets","emoji":"🥮"}'::jsonb),
('gulab_jamun', '{"name":"Gulab Jamun","cals":150,"p":2,"c":25,"f":5,"unit":"item","category":"sweets","emoji":"🍘"}'::jsonb),
('jalebi', '{"name":"Jalebi (2 pcs)","cals":200,"p":1,"c":40,"f":4,"unit":"plate","category":"sweets","emoji":"🥨"}'::jsonb),
('rasgulla', '{"name":"Rasgulla (2 pcs)","cals":150,"p":4,"c":30,"f":2,"unit":"plate","category":"sweets","emoji":"⚪"}'::jsonb),
('vanilla_ice_cream', '{"name":"Vanilla Ice Cream","cals":140,"p":2,"c":16,"f":7,"unit":"scoop","category":"sweets","emoji":"🍦"}'::jsonb),
('chocolate_bar', '{"name":"Chocolate Bar (Dairy Milk)","cals":260,"p":3,"c":30,"f":14,"unit":"item","category":"sweets","emoji":"🍫"}'::jsonb),
('cake_slice', '{"name":"Cake Slice (Sponge)","cals":250,"p":3,"c":35,"f":10,"unit":"slice","category":"sweets","emoji":"🍰"}'::jsonb),
('brownie', '{"name":"Chocolate Brownie","cals":300,"p":4,"c":40,"f":15,"unit":"item","category":"sweets","emoji":"🥮"}'::jsonb),
('kheer_rice', '{"name":"Rice Kheer","cals":280,"p":5,"c":45,"f":8,"unit":"bowl","category":"sweets","emoji":"🥣"}'::jsonb),
('double_ka_meetha', '{"name":"Double Ka Meetha","cals":350,"p":6,"c":45,"f":16,"unit":"bowl","category":"sweets","emoji":"🍞"}'::jsonb),
('mysore_pak', '{"name":"Mysore Pak","cals":200,"p":2,"c":20,"f":12,"unit":"item","category":"sweets","emoji":"🥮"}'::jsonb),
('barfi', '{"name":"Kaju Katli/Barfi","cals":60,"p":1,"c":8,"f":3,"unit":"item","category":"sweets","emoji":"💠"}'::jsonb),
('chocolate_ice_cream', '{"name":"Chocolate Ice Cream","cals":160,"p":3,"c":18,"f":8,"unit":"scoop","category":"sweets","emoji":"🍨"}'::jsonb),
('banana_chips', '{"name":"Banana Chips","cals":150,"p":1,"c":18,"f":8,"unit":"bowl","category":"snacks","emoji":"🍌"}'::jsonb),
('murukku', '{"name":"Murukku / Chakli","cals":120,"p":2,"c":14,"f":6,"unit":"item","category":"snacks","emoji":"🥨"}'::jsonb),
('mixture_south', '{"name":"South Indian Mixture","cals":250,"p":5,"c":20,"f":16,"unit":"bowl","category":"snacks","emoji":"🥜"}'::jsonb),
('biscuit_cream', '{"name":"Cream Biscuit (2 pcs)","cals":100,"p":1,"c":15,"f":4,"unit":"item","category":"snacks","emoji":"🍪"}'::jsonb),
('almonds', '{"name":"Almonds","cals":164,"p":6,"c":6,"f":14,"unit":"g","category":"snacks","emoji":"🌰"}'::jsonb),
('cashews', '{"name":"Cashews","cals":157,"p":5,"c":9,"f":12,"unit":"g","category":"snacks","emoji":"🌰"}'::jsonb),
('peanuts', '{"name":"Peanuts (Roasted)","cals":161,"p":7,"c":5,"f":14,"unit":"g","category":"snacks","emoji":"🥜"}'::jsonb),
('peanut_butter', '{"name":"Peanut Butter","cals":190,"p":8,"c":6,"f":16,"unit":"tbsp","category":"snacks","emoji":"🥜"}'::jsonb),
('dates_dried', '{"name":"Dates (2 pcs)","cals":40,"p":0,"c":11,"f":0,"unit":"item","category":"snacks","emoji":"🏜️"}'::jsonb),
('raisins', '{"name":"Raisins","cals":85,"p":1,"c":22,"f":0,"unit":"bowl","category":"snacks","emoji":"🍇"}'::jsonb),
('popcorn', '{"name":"Popcorn (Air popped)","cals":90,"p":3,"c":18,"f":1,"unit":"bowl","category":"snacks","emoji":"🍿"}'::jsonb),
('nachos_cheese', '{"name":"Nachos & Cheese","cals":350,"p":6,"c":40,"f":18,"unit":"plate","category":"snacks","emoji":"🧀"}'::jsonb),
('chips_potato', '{"name":"Potato Chips","cals":160,"p":2,"c":15,"f":10,"unit":"bowl","category":"snacks","emoji":"🥔"}'::jsonb),
('roasted_chana', '{"name":"Roasted Chana","cals":120,"p":6,"c":18,"f":2,"unit":"bowl","category":"snacks","emoji":"🧆"}'::jsonb),
('trail_mix', '{"name":"Trail Mix","cals":140,"p":4,"c":12,"f":9,"unit":"bowl","category":"snacks","emoji":"🥜"}'::jsonb),
('whey_protein', '{"name":"Whey Protein Isolate","cals":110,"p":25,"c":1,"f":0,"unit":"scoop","category":"fitness","emoji":"🥛"}'::jsonb),
('oats_raw', '{"name":"Rolled Oats (Raw)","cals":389,"p":17,"c":66,"f":7,"unit":"g","category":"fitness","emoji":"🌾"}'::jsonb),
('peanut_butter_natural', '{"name":"Natural Peanut Butter","cals":190,"p":8,"c":6,"f":16,"unit":"tbsp","category":"fitness","emoji":"🥜"}'::jsonb),
('greek_yogurt_plain', '{"name":"Greek Yogurt 0%","cals":59,"p":10,"c":4,"f":0,"unit":"g","category":"fitness","emoji":"🥣"}'::jsonb),
('almonds_raw', '{"name":"Raw Almonds","cals":164,"p":6,"c":6,"f":14,"unit":"g","category":"fitness","emoji":"🌰"}'::jsonb),
('sweet_potato_baked', '{"name":"Baked Sweet Potato","cals":90,"p":2,"c":21,"f":0,"unit":"g","category":"fitness","emoji":"🍠"}'::jsonb),
('quinoa', '{"name":"Quinoa (Cooked)","cals":120,"p":4,"c":21,"f":2,"unit":"g","category":"fitness","emoji":"🍚"}'::jsonb),
('avocado', '{"name":"Avocado","cals":160,"p":2,"c":9,"f":15,"unit":"g","category":"fitness","emoji":"🥑"}'::jsonb),
('olive_oil', '{"name":"Olive Oil","cals":120,"p":0,"c":0,"f":14,"unit":"tbsp","category":"fitness","emoji":"🫒"}'::jsonb),
('brown_bread', '{"name":"100% Whole Wheat Bread","cals":80,"p":4,"c":14,"f":1,"unit":"slice","category":"fitness","emoji":"🍞"}'::jsonb),
('chia_seeds', '{"name":"Chia Seeds","cals":138,"p":5,"c":12,"f":9,"unit":"tbsp","category":"fitness","emoji":"🌱"}'::jsonb),
('flax_seeds', '{"name":"Flax Seeds","cals":150,"p":5,"c":8,"f":11,"unit":"tbsp","category":"fitness","emoji":"🌱"}'::jsonb),
('granola', '{"name":"Granola (Low Sugar)","cals":120,"p":3,"c":16,"f":5,"unit":"bowl","category":"fitness","emoji":"🥣"}'::jsonb),
('protein_bar', '{"name":"Protein Bar","cals":200,"p":20,"c":22,"f":7,"unit":"item","category":"fitness","emoji":"🍫"}'::jsonb),
('egg_whites_liquid', '{"name":"Liquid Egg Whites","cals":54,"p":11,"c":1,"f":0,"unit":"g","category":"fitness","emoji":"🥚"}'::jsonb),
('banana', '{"name":"Banana","cals":105,"p":1,"c":27,"f":0,"unit":"item","category":"fruits","emoji":"🍌"}'::jsonb),
('apple', '{"name":"Apple","cals":95,"p":0,"c":25,"f":0,"unit":"item","category":"fruits","emoji":"🍎"}'::jsonb),
('mango', '{"name":"Mango","cals":200,"p":1,"c":50,"f":1,"unit":"item","category":"fruits","emoji":"🥭"}'::jsonb),
('orange', '{"name":"Orange","cals":62,"p":1,"c":15,"f":0,"unit":"item","category":"fruits","emoji":"🍊"}'::jsonb),
('watermelon', '{"name":"Watermelon","cals":30,"p":0,"c":8,"f":0,"unit":"g","category":"fruits","emoji":"🍉"}'::jsonb),
('grapes', '{"name":"Grapes","cals":69,"p":1,"c":18,"f":0,"unit":"g","category":"fruits","emoji":"🍇"}'::jsonb),
('papaya', '{"name":"Papaya","cals":43,"p":0,"c":11,"f":0,"unit":"g","category":"fruits","emoji":"🫒"}'::jsonb),
('pineapple', '{"name":"Pineapple","cals":50,"p":0,"c":13,"f":0,"unit":"g","category":"fruits","emoji":"🍍"}'::jsonb),
('pomegranate', '{"name":"Pomegranate","cals":83,"p":1,"c":19,"f":1,"unit":"g","category":"fruits","emoji":"🍎"}'::jsonb),
('guava', '{"name":"Guava","cals":68,"p":2,"c":14,"f":1,"unit":"item","category":"fruits","emoji":"🍐"}'::jsonb),
('strawberry', '{"name":"Strawberry","cals":32,"p":0,"c":8,"f":0,"unit":"g","category":"fruits","emoji":"🍓"}'::jsonb),
('kiwi', '{"name":"Kiwi","cals":42,"p":0,"c":10,"f":0,"unit":"item","category":"fruits","emoji":"🥝"}'::jsonb),
('whole_milk_dairy', '{"name":"Whole Milk","cals":61,"p":3,"c":4,"f":3,"unit":"ml","category":"dairy","emoji":"🥛"}'::jsonb),
('skim_milk_dairy', '{"name":"Skim Milk","cals":34,"p":3,"c":5,"f":0,"unit":"ml","category":"dairy","emoji":"🥛"}'::jsonb),
('curd_dairy', '{"name":"Curd/Yogurt","cals":98,"p":3,"c":4,"f":4,"unit":"g","category":"dairy","emoji":"🥣"}'::jsonb),
('paneer_raw', '{"name":"Paneer","cals":296,"p":14,"c":3,"f":25,"unit":"g","category":"dairy","emoji":"🧀"}'::jsonb),
('cheese_slice', '{"name":"Cheese Slice","cals":85,"p":5,"c":1,"f":7,"unit":"slice","category":"dairy","emoji":"🧀"}'::jsonb),
('butter_dairy', '{"name":"Butter","cals":102,"p":0,"c":0,"f":11,"unit":"tbsp","category":"dairy","emoji":"🧈"}'::jsonb),
('ghee', '{"name":"Ghee","cals":112,"p":0,"c":0,"f":13,"unit":"tbsp","category":"dairy","emoji":"🧈"}'::jsonb),
('cream_dairy', '{"name":"Fresh Cream","cals":345,"p":2,"c":3,"f":36,"unit":"g","category":"dairy","emoji":"🍦"}'::jsonb),
('condensed_milk', '{"name":"Condensed Milk","cals":321,"p":8,"c":54,"f":8,"unit":"g","category":"dairy","emoji":"🥛"}'::jsonb),
('buttermilk_dairy', '{"name":"Buttermilk","cals":40,"p":3,"c":4,"f":1,"unit":"cup","category":"dairy","emoji":"🥛"}'::jsonb),
('pasta_cooked', '{"name":"Pasta (Cooked)","cals":131,"p":5,"c":25,"f":1,"unit":"g","category":"international","emoji":"🍝"}'::jsonb),
('spaghetti_bolognese', '{"name":"Spaghetti Bolognese","cals":450,"p":25,"c":50,"f":15,"unit":"plate","category":"international","emoji":"🍝"}'::jsonb),
('margherita_pizza_full', '{"name":"Margherita Pizza (Whole)","cals":1200,"p":45,"c":130,"f":45,"unit":"item","category":"international","emoji":"🍕"}'::jsonb),
('chicken_wrap', '{"name":"Chicken Wrap","cals":350,"p":20,"c":35,"f":14,"unit":"item","category":"international","emoji":"🌯"}'::jsonb),
('club_sandwich', '{"name":"Club Sandwich","cals":450,"p":22,"c":40,"f":20,"unit":"item","category":"international","emoji":"🥪"}'::jsonb),
('caesar_salad', '{"name":"Caesar Salad (with chicken)","cals":350,"p":25,"c":12,"f":22,"unit":"bowl","category":"international","emoji":"🥗"}'::jsonb),
('tom_yum_soup', '{"name":"Tom Yum Soup","cals":120,"p":8,"c":10,"f":4,"unit":"bowl","category":"international","emoji":"🥣"}'::jsonb),
('sushi_roll', '{"name":"Sushi Roll (Salmon/Tuna)","cals":300,"p":12,"c":45,"f":5,"unit":"item","category":"international","emoji":"🍣"}'::jsonb),
('burrito', '{"name":"Chicken Burrito","cals":550,"p":28,"c":65,"f":20,"unit":"item","category":"international","emoji":"🌯"}'::jsonb),
('taco', '{"name":"Beef Taco","cals":200,"p":10,"c":15,"f":10,"unit":"item","category":"international","emoji":"🌮"}'::jsonb),
('steak_ribeye', '{"name":"Ribeye Steak","cals":290,"p":24,"c":0,"f":22,"unit":"g","category":"international","emoji":"🥩"}'::jsonb),
('grilled_chicken_plate', '{"name":"Grilled Chicken & Veggies","cals":350,"p":40,"c":15,"f":12,"unit":"plate","category":"international","emoji":"🍗"}'::jsonb),
('fish_and_chips', '{"name":"Fish & Chips","cals":750,"p":25,"c":65,"f":40,"unit":"plate","category":"international","emoji":"🍟"}'::jsonb),
('pad_thai', '{"name":"Pad Thai","cals":500,"p":18,"c":65,"f":18,"unit":"plate","category":"international","emoji":"🍜"}'::jsonb),
('ramen', '{"name":"Tonkotsu Ramen","cals":650,"p":25,"c":60,"f":30,"unit":"bowl","category":"international","emoji":"🍜"}'::jsonb)
ON CONFLICT (food_key) DO UPDATE SET data = EXCLUDED.data;

-- Robot Messages
INSERT INTO robot_messages (scenario, mode, message)
VALUES
('morning_empty', 'good', 'Rise and grind! Ready to absolutely crush these macros?'),
('morning_empty', 'good', 'The sun is up and your calorie budget is pristine. Let''s get to work.'),
('morning_empty', 'good', 'Good morning! Your muscles are hungry, feed them right.'),
('morning_empty', 'good', 'A new day, a clean slate. Let''s make it a masterpiece.'),
('morning_empty', 'good', 'Morning coach! Hydrate and let''s get that first meal in.'),
('morning_empty', 'normal', 'Good morning. Dashboard is zeroed out. Awaiting input.'),
('morning_empty', 'normal', 'Time to break the fast.'),
('morning_empty', 'normal', 'Morning. Log your breakfast when ready.'),
('morning_empty', 'normal', 'Awaiting initial calorie intake data.'),
('morning_empty', 'normal', 'System initialized. Ready for today''s logs.'),
('morning_empty', 'bad', 'Are we photosynthesizing today or did you forget to log?'),
('morning_empty', 'bad', 'Wakey wakey. Fasting won''t save you from a bad diet.'),
('morning_empty', 'bad', 'I see a lot of zeros. A diet requires actually tracking things.'),
('morning_empty', 'bad', 'Good morning. Still asleep, or just ignoring your macros?'),
('morning_empty', 'bad', 'Your metabolism is waiting. Stop procrastinating and eat.'),
('morning_active', 'good', 'Great start! That''s how you set the tone for the day.'),
('morning_active', 'good', 'Breakfast of champions officially logged.'),
('morning_active', 'good', 'Solid early momentum. Keep this energy going!'),
('morning_active', 'good', 'Love the morning protein hit. Synthesis engaged.'),
('morning_active', 'good', 'Already moving the needle! Let''s keep it clean.'),
('morning_active', 'normal', 'Morning calories registered.'),
('morning_active', 'normal', 'Initial meal tracked.'),
('morning_active', 'normal', 'Breakfast logged. Proceeding with the day.'),
('morning_active', 'normal', 'Data received. Keep tracking.'),
('morning_active', 'normal', 'Off to a standard start.'),
('morning_active', 'bad', 'You call that breakfast? Better make up for it later.'),
('morning_active', 'bad', 'Finally, some food. Let''s hope lunch is better planned.'),
('morning_active', 'bad', 'Logged. Try not to ruin your macros by noon.'),
('morning_active', 'bad', 'Decent start. Don''t let the afternoon slump ruin it.'),
('morning_active', 'bad', 'I recorded that. I''m judging it, but I recorded it.'),
('afternoon_check', 'good', 'Halfway through the day and looking strong!'),
('afternoon_check', 'good', 'Afternoon check-in! You''re pacing perfectly.'),
('afternoon_check', 'good', 'Crushing it today! Keep the discipline high.'),
('afternoon_check', 'good', 'The afternoon is where legends are made. Stay focused!'),
('afternoon_check', 'good', 'Solid tracking so far. Let''s nail the evening.'),
('afternoon_check', 'normal', 'Afternoon status: ongoing.'),
('afternoon_check', 'normal', 'Half the day is gone. Review your remaining macros.'),
('afternoon_check', 'normal', 'Midday check. Keep logging.'),
('afternoon_check', 'normal', 'Afternoon. Stay on budget.'),
('afternoon_check', 'normal', 'Tracking is active.'),
('afternoon_check', 'bad', 'Afternoon slump hitting? Put down the chips.'),
('afternoon_check', 'bad', 'Half the day gone and your macros look like a crime scene.'),
('afternoon_check', 'bad', 'Don''t let a 3 PM sugar craving destroy your progress.'),
('afternoon_check', 'bad', 'I see you slipping. Reign it in before dinner.'),
('afternoon_check', 'bad', 'Midday review: You can do better than this.'),
('evening_push', 'good', 'Almost done! Finish strong and secure the win.'),
('evening_push', 'good', 'The day is wrapping up. You''ve done great so far!'),
('evening_push', 'good', 'Evening is here. Let''s close out these macros perfectly.'),
('evening_push', 'good', 'Just dinner left. You''ve got this in the bag.'),
('evening_push', 'good', 'Excellent discipline today. Bring it home!'),
('evening_push', 'normal', 'Evening approaching. Log your final meals.'),
('evening_push', 'normal', 'Review your remaining budget for dinner.'),
('evening_push', 'normal', 'Day is ending. Check your totals.'),
('evening_push', 'normal', 'Almost over. Stay aware of your target.'),
('evening_push', 'normal', 'Evening log required.'),
('evening_push', 'bad', 'Nighttime cravings are a trap. Don''t ruin today.'),
('evening_push', 'bad', 'Late-night snacking is how diets die. Step away from the fridge.'),
('evening_push', 'bad', 'Don''t undo a whole day of work with a midnight binge.'),
('evening_push', 'bad', 'The sun is down, which means your willpower is dropping. Stay strong.'),
('evening_push', 'bad', 'I''m watching your evening calories. Don''t disappoint me.'),
('perfect_macros', 'good', 'Flawless macros! You are an absolute machine today!'),
('perfect_macros', 'good', 'Chef''s kiss! That macro split is a work of art.'),
('perfect_macros', 'good', 'Perfect protein, carbs, and fat. Text-book execution!'),
('perfect_macros', 'good', 'This is how you build a physique. Incredible precision.'),
('perfect_macros', 'good', 'Nailed the macros perfectly. Outstanding dedication!'),
('perfect_macros', 'normal', 'Macros are exactly on point.'),
('perfect_macros', 'normal', 'Optimal macro distribution achieved.'),
('perfect_macros', 'normal', 'Protein, carbs, and fat targets met.'),
('perfect_macros', 'normal', 'Macro ratio is optimal.'),
('perfect_macros', 'normal', 'Precise logging today.'),
('perfect_macros', 'bad', 'Perfect macros? Let me guess, you used a calculator to round it out.'),
('perfect_macros', 'bad', 'Wow, perfect macros. Must be a glitch in the matrix.'),
('perfect_macros', 'bad', 'You actually hit your macros. Try doing it twice in a row.'),
('perfect_macros', 'bad', 'I''m shocked. You actually followed the plan today.'),
('perfect_macros', 'bad', 'Enjoy the perfect score. Tomorrow is a new day to mess up.'),
('target_hit', 'good', 'Bullseye! You hit your exact calorie target!'),
('target_hit', 'good', 'Perfection! Exactly what we aimed for today.'),
('target_hit', 'good', 'Amazing precision! You are a master of tracking.'),
('target_hit', 'good', 'Target hit! Your metabolism thanks you.'),
('target_hit', 'good', 'Flawless victory today! Rest easy.'),
('target_hit', 'normal', 'Target achieved.'),
('target_hit', 'normal', 'Calories match goal perfectly.'),
('target_hit', 'normal', 'Goal met for today.'),
('target_hit', 'normal', 'Budget exhausted exactly.'),
('target_hit', 'normal', 'Mission accomplished.'),
('target_hit', 'bad', 'About time you actually hit the target.'),
('target_hit', 'bad', 'You finally followed the plan. Was it that hard?'),
('target_hit', 'bad', 'Target hit. Let''s see if you can repeat this miracle.'),
('target_hit', 'bad', 'Don''t get cocky. One good day doesn''t erase a bad week.'),
('target_hit', 'bad', 'Okay, you hit it. Now do it again tomorrow.'),
('near_target', 'good', 'So close! Practically perfect tracking today!'),
('near_target', 'good', 'Within the margin of error. Brilliant job!'),
('near_target', 'good', 'Basically nailed it. That''s a huge win!'),
('near_target', 'good', 'Excellent restraint, finishing right on the edge of the goal.'),
('near_target', 'good', 'Great work! Just shy of perfect, but totally effective.'),
('near_target', 'normal', 'Close enough to target.'),
('near_target', 'normal', 'Acceptable variance.'),
('near_target', 'normal', 'Near goal.'),
('near_target', 'normal', 'Within acceptable limits.'),
('near_target', 'normal', 'Almost exact.'),
('near_target', 'bad', 'Close, but no cigar. Try harder tomorrow.'),
('near_target', 'bad', 'Almost there, but ''almost'' doesn''t build muscle.'),
('near_target', 'bad', 'Missed the exact mark. Precision matters.'),
('near_target', 'bad', 'Sloppy ending. You couldn''t just hit the number?'),
('near_target', 'bad', 'You were so close, yet you failed.'),
('over_minor', 'good', 'Slightly over, but totally manageable. Great day overall!'),
('over_minor', 'good', 'A little extra fuel today. Put it to use in your next workout!'),
('over_minor', 'good', 'Just a tiny bump over the line. Nothing a walk can''t fix.'),
('over_minor', 'good', 'Don''t sweat the small stuff. You''re still on a great path.'),
('over_minor', 'good', 'A few extra calories won''t derail you. Stay positive!'),
('over_minor', 'normal', 'Slightly over target.'),
('over_minor', 'normal', 'Calorie goal exceeded marginally.'),
('over_minor', 'normal', 'Over budget by a small amount.'),
('over_minor', 'normal', 'Minor surplus detected.'),
('over_minor', 'normal', 'A little extra today.'),
('over_minor', 'bad', 'Slipping up? Those ''little bites'' add up fast.'),
('over_minor', 'bad', 'A minor failure is still a failure. Reign it in.'),
('over_minor', 'bad', 'You couldn''t just stop eating 5 minutes earlier?'),
('over_minor', 'bad', 'Slightly over. Discipline is doing what you hate, do it.'),
('over_minor', 'bad', 'Those extra calories are going straight to your waistline.'),
('over_major', 'good', 'Oops, a bit of a blowout! It happens to everyone. Reset tomorrow!'),
('over_major', 'good', 'We all have high-calorie days. Don''t stress, just bounce back!'),
('over_major', 'good', 'A heavy day! Use that extra energy to crush a workout tomorrow.'),
('over_major', 'good', 'Don''t let one bad day ruin your week. Forgive yourself and move on.'),
('over_major', 'good', 'Big surplus today. Remember: consistency beats perfection!'),
('over_major', 'normal', 'Significantly over target.'),
('over_major', 'normal', 'Calorie goal exceeded heavily.'),
('over_major', 'normal', 'Way over budget.'),
('over_major', 'normal', 'Major surplus recorded.'),
('over_major', 'normal', 'Excessive intake detected.'),
('over_major', 'bad', 'Absolute disaster. Did you eat a horse?'),
('over_major', 'bad', 'This is why you aren''t reaching your goals. Zero self-control.'),
('over_major', 'bad', 'What a mess. Tomorrow better be an absolute masterclass in fasting.'),
('over_major', 'bad', 'A 400+ calorie surplus? So much for the summer body.'),
('over_major', 'bad', 'I''m updating your profile to ''professional competitive eater''.'),
('high_sugar', 'good', 'Enjoyed some treats today! Balance is key to a sustainable diet.'),
('high_sugar', 'good', 'Got that sweet tooth out of the system! Back to whole foods tomorrow.'),
('high_sugar', 'good', 'A sugary day! Fueling up for some high-intensity work!'),
('high_sugar', 'normal', 'High proportion of sugar detected.'),
('high_sugar', 'normal', 'Carbs primarily sourced from sweets.'),
('high_sugar', 'normal', 'Sugar intake is elevated.'),
('high_sugar', 'bad', 'Are you 5 years old? Stop eating so much candy.'),
('high_sugar', 'bad', 'A massive sugar spike. Enjoy the inevitable crash.'),
('high_sugar', 'bad', 'Tracking macros doesn''t mean you should fill them with garbage.'),
('high_fast_food', 'good', 'Treated yourself today! Nothing wrong with a quick meal.'),
('high_fast_food', 'good', 'Fast food day! As long as it fits your macros, you''re fine.'),
('high_fast_food', 'good', 'Enjoy the convenience! Tomorrow we cook.'),
('high_fast_food', 'normal', 'Fast food detected in logs.'),
('high_fast_food', 'normal', 'Dietary source: Quick service.'),
('high_fast_food', 'normal', 'High sodium intake likely.'),
('high_fast_food', 'bad', 'Fast food again? Your arteries are begging for mercy.'),
('high_fast_food', 'bad', 'The scale is going to spike tomorrow from all that sodium.'),
('high_fast_food', 'bad', 'You are literally made of what you eat. Today, you are trash.'),
('liquid_diet', 'good', 'Shakes on shakes! Getting that quick protein in!'),
('liquid_diet', 'good', 'Liquid fuel today! Easy digestion.'),
('liquid_diet', 'good', 'Supplementing hard! Keep grinding.'),
('liquid_diet', 'normal', 'High proportion of liquid calories/supplements.'),
('liquid_diet', 'normal', 'Solid food intake is low.'),
('liquid_diet', 'normal', 'Relying heavily on fitness foods.'),
('liquid_diet', 'bad', 'You''re living on whey protein. Eat a real piece of meat.'),
('liquid_diet', 'bad', 'Drinkable calories won''t keep you full. You''re going to starve later.'),
('liquid_diet', 'bad', 'Chew your food once in a while. Real food matters.'),
('carnivore', 'good', 'Meat machine! Building that dense muscle.'),
('carnivore', 'good', 'Incredible protein sourcing today. Pure gains.'),
('carnivore', 'good', 'Carnivore style! Your recovery is going to be insane.'),
('carnivore', 'normal', 'High proportion of meat consumed.'),
('carnivore', 'normal', 'Protein sourced heavily from animals.'),
('carnivore', 'normal', 'Meat-heavy day.'),
('carnivore', 'bad', 'Did you spare any animals today? Eat a vegetable.'),
('carnivore', 'bad', 'Your digestion must be working overtime right now.'),
('carnivore', 'bad', 'Meat is great, but fiber exists for a reason.'),
('streak_3', 'good', '3 days strong! The habit is taking root!'),
('streak_3', 'good', 'Three in a row! You are on absolute fire!'),
('streak_3', 'good', 'A solid 3-day streak! I love this momentum!'),
('streak_3', 'normal', '3 day streak.'),
('streak_3', 'normal', 'Streak of 3 reached.'),
('streak_3', 'normal', 'Three days on track.'),
('streak_3', 'bad', '3 days is a warmup. Keep going.'),
('streak_3', 'bad', 'Don''t celebrate a 3-day streak. Give me 30.'),
('streak_3', 'bad', 'Three days. Try not to break it this weekend.'),
('streak_7', 'good', 'A whole week! You are officially unstoppable!'),
('streak_7', 'good', '7 days of perfection! Incredible discipline!'),
('streak_7', 'good', 'One full week down! Your body is adapting!'),
('streak_7', 'normal', '7 day streak achieved.'),
('streak_7', 'normal', 'One full week on target.'),
('streak_7', 'normal', 'Streak: 7 days.'),
('streak_7', 'bad', 'A week. Not bad... for you.'),
('streak_7', 'bad', 'Seven days. Now the real test begins.'),
('streak_7', 'bad', 'Don''t let a 7-day streak inflate your ego.'),
('streak_30', 'good', '30 DAYS! You are an absolute legend!'),
('streak_30', 'good', 'A month of pure dedication. This is life-changing!'),
('streak_30', 'good', '30 day streak! I am genuinely proud of you!'),
('streak_30', 'normal', '30 day streak.'),
('streak_30', 'normal', 'One month on track.'),
('streak_30', 'normal', 'Streak of 30 days.'),
('streak_30', 'bad', '30 days. Okay, I am slightly impressed.'),
('streak_30', 'bad', 'A whole month. Finally, some actual discipline.'),
('streak_30', 'bad', '30 days down. Don''t ruin it on day 31.'),
('streak_broken', 'good', 'Streak broken, but that''s okay! Start a new one today!'),
('streak_broken', 'good', 'Don''t let one slip ruin your momentum. Bounce back!'),
('streak_broken', 'good', 'A streak ends, but the journey continues. You got this!'),
('streak_broken', 'normal', 'Streak lost.'),
('streak_broken', 'normal', 'Back to zero.'),
('streak_broken', 'normal', 'Streak broken today.'),
('streak_broken', 'bad', 'And... the streak is dead. Pathetic.'),
('streak_broken', 'bad', 'All that hard work, ruined by zero self-control.'),
('streak_broken', 'bad', 'Back to day one. Try not to mess it up this time.'),
('first_day', 'good', 'Welcome! Let''s crush these goals together!'),
('first_day', 'good', 'Day 1! The beginning of a stronger you!'),
('first_day', 'good', 'So happy you''re here. Let''s make every calorie count!'),
('first_day', 'normal', 'First day tracking.'),
('first_day', 'normal', 'Welcome to the app.'),
('first_day', 'normal', 'Log your first meal.'),
('first_day', 'bad', 'Day 1. Let''s see how long you actually last.'),
('first_day', 'bad', 'Welcome. Don''t give up in a week like you usually do.'),
('first_day', 'bad', 'First day. Prove you actually have what it takes.')
ON CONFLICT ON CONSTRAINT robot_messages_scenario_mode_message_key DO NOTHING;

-- Insight Texts
INSERT INTO insight_texts (insight_key, mode, message)
VALUES
('morning_empty_early', 'good', 'Start your day right. A protein-rich breakfast sets the metabolic tone.'),
('morning_empty_early', 'normal', 'Breakfast window is open. Awaiting initial logs.'),
('morning_empty_early', 'bad', 'Don''t even think about skipping breakfast and complaining about hunger later.'),
('morning_empty_mid', 'good', 'Half the day is gone and you haven''t logged. Don''t fall into the trap of guessing later.'),
('morning_empty_mid', 'normal', 'No data received by midday.'),
('morning_empty_mid', 'bad', 'No logs by noon? You''re setting yourself up for an evening binge.'),
('fasting', 'good', 'Fasting today? Make sure you hydrate!'),
('fasting', 'normal', 'Zero calories recorded. Day is almost over.'),
('fasting', 'bad', 'Fasting? If not, you are playing a dangerous game with your macros right now.'),
('high_sugar', 'good', 'Enjoyed the treats! Just be mindful of an energy dip later.'),
('high_sugar', 'normal', 'High ratio of calories derived from sweets.'),
('high_sugar', 'bad', 'High sugar intake today. Expect a massive crash. Your pancreas hates you.'),
('high_fast_food', 'good', 'Treated yourself to some takeout! Drink extra water today to balance the sodium.'),
('high_fast_food', 'normal', 'High fast food ratio detected. Sodium levels elevated.'),
('high_fast_food', 'bad', 'Heavy on the fast food today. The scale is going to spike tomorrow from sodium retention. Stop poisoning yourself.'),
('high_fitness', 'good', 'Getting that easy protein in! Try to get some whole foods later for better digestion.'),
('high_fitness', 'normal', 'Supplement dependency high today.'),
('high_fitness', 'bad', 'You''re living on powders and bars. Eat some actual solid food, you''re not an astronaut.'),
('backloading', 'good', 'Backloading calories today! Make sure you don''t go to bed feeling too full.'),
('backloading', 'normal', 'All calories consumed in the evening window.'),
('backloading', 'bad', 'You skipped the entire morning and are backloading all calories now. Your digestion is going to hate you.'),
('frontloading', 'good', 'You''ve eaten most of your food early! You''ll need serious willpower tonight.'),
('frontloading', 'normal', '80% budget exhausted before 14:00.'),
('frontloading', 'bad', 'You''ve burned through 80% of your calories before 2 PM. Tonight is going to be a miserable test of willpower.'),
('over_cut', 'good', 'You blew past your cutting target. Acknowledge it, log it, and reset tomorrow. No guilt!'),
('over_cut', 'normal', 'Surplus detected during cut phase.'),
('over_cut', 'bad', 'You blew past your deficit. This is exactly why you aren''t losing weight. Do better tomorrow.'),
('over_general', 'good', 'Over target today. Tomorrow''s a reset — not a reason to spiral into a binge.'),
('over_general', 'normal', 'Daily calorie budget exceeded.'),
('over_general', 'bad', 'Over your target. Again. A complete lack of dietary discipline.'),
('perfect', 'good', 'Absolute perfection. Calories nailed, protein hit. This is how you change your body.'),
('perfect', 'normal', 'Calories and protein precisely on target.'),
('perfect', 'bad', 'You actually hit your calories and protein perfectly. I''m genuinely shocked.'),
('target_hit', 'good', 'Right on your calorie target! Consistency like this is what drives real results.'),
('target_hit', 'normal', 'Calorie goal achieved.'),
('target_hit', 'bad', 'You hit your calories, but missed the protein. Don''t get sloppy.'),
('protein_deficit', 'good', 'You have calories left but are missing protein. Lean meats are your best friends right now.'),
('protein_deficit', 'normal', 'Protein deficit detected.'),
('protein_deficit', 'bad', 'You have room for food but you''re missing protein. Eat some chicken before you lose all your muscle.'),
('bulk_deficit', 'good', 'You''re leaving gains on the table! Eat those remaining calories if you want to grow.'),
('bulk_deficit', 'normal', 'Large surplus required for bulk is unmet.'),
('bulk_deficit', 'bad', 'You''re trying to bulk but skipping meals? Eat your food or stay small forever.'),
('low_remaining', 'good', 'Very few calories left but it''s early. Time to master the art of high-volume, low-calorie foods.'),
('low_remaining', 'normal', 'Low remaining budget early in the day.'),
('low_remaining', 'bad', 'Very few calories left and the sun is still out. You''re going to be starving tonight. Poor planning.'),
('mid_remaining', 'good', 'Budget running low. Plan your remaining meals wisely!'),
('mid_remaining', 'normal', 'Budget over half exhausted.'),
('mid_remaining', 'bad', 'Running low on calories. Don''t blow it all on one stupid snack.'),
('streak_milestone', 'good', 'Days straight of logging! This isn''t just a diet anymore, it''s your lifestyle!'),
('streak_milestone', 'normal', 'Weekly milestone tracked.'),
('streak_milestone', 'bad', 'Streak logged. Finally showing a shred of consistency.'),
('high_meat', 'good', 'Solid protein foundation today. Carnivore style!'),
('high_meat', 'normal', 'Dietary source: predominantly meat.'),
('high_meat', 'bad', 'Eating like a pure carnivore today. Hope your digestion can handle it.'),
('high_plant', 'good', 'Great micronutrient profile today. Keep eating those plants!'),
('high_plant', 'normal', 'Plant-based nutrient intake is optimal.'),
('high_plant', 'bad', 'Actually eating your vegetables today. Look at you acting like an adult.'),
('default', 'good', 'Every entry builds the habit. Trust the data, trust the process.'),
('default', 'normal', 'Data logging is active and proceeding normally.'),
('default', 'bad', 'Just keep logging. The math doesn''t care about your feelings.')
ON CONFLICT (insight_key, mode) DO UPDATE SET message = EXCLUDED.message;
